/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package chikamune.minoru.pedometer;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int title_bg_color=0x7f040001;
        public static final int title_text_color=0x7f040000;
    }
    public static final class dimen {
        public static final int title_textsize=0x7f050000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int reset_button=0x7f070006;
        public static final int start=0x7f070002;
        public static final int steps=0x7f070005;
        public static final int steps_label=0x7f070004;
        public static final int stop=0x7f070003;
        public static final int title=0x7f070001;
        public static final int widget56=0x7f070000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int title=0x7f060001;
    }
}
