application: android-scouter
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.py

- url: /data/.*
  script: data.py

- url: /.*
  script: help.py


