/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package android.Screen.TestView;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int moshimoshi=0x7f020001;
        public static final int stat_sample=0x7f020002;
    }
    public static final class id {
        public static final int imageview=0x7f050003;
        public static final int layout_textview01=0x7f050000;
        public static final int layout_textview02=0x7f050001;
        public static final int layout_textview03=0x7f050002;
    }
    public static final class layout {
        public static final int disply_view=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int alarm_service_finished=0x7f040004;
        public static final int alarm_service_label=0x7f040005;
        public static final int alarm_service_started=0x7f040003;
        public static final int app_name=0x7f040001;
        public static final int device_id=0x7f040008;
        public static final int hello=0x7f040000;
        public static final int repeating_scheduled=0x7f040002;
        public static final int update_ip_addr=0x7f040006;
        public static final int update_port=0x7f040007;
    }
}
