application: remoteapitest
version: 1 
runtime: python
api_version: 1

handlers:
- url: /console/static
  static_dir: console/app/view/static
  login: admin

- url: /console.*
  script: console/app/console.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: main.py
